library(mosaic)
library(readr)
acm_autonomous_vehicles <- read_csv("D:/dev/fom/Thesis/data/acm_autonomous_vehicles.csv")
# View(acm_autonomous_vehicles)
wos_autonomous_vehicles <- read_csv("D:/dev/fom/Thesis/data/wos_autonomous_vehicles.txt")
# View(wos_autonomous_vehicles)
ieee_autonomous_vehicles <- read_csv("D:/dev/fom/Thesis/data/ieee_autonomous_vehicles-2.csv")
# View(ieee_autonomous_vehicles)
inspect(acm_autonomous_vehicles)
favstats(~year,data=acm_autonomous_vehicles)
favstats(~PY,data=wos_autonomous_vehicles)
favstats(~Publication_Year,data=ieee_autonomous_vehicles)
